// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qulxkesbttlypmpzkhhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bHhrZXNidHRseXBtcHpraGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjE3MTcsImV4cCI6MjA2Nzc5NzcxN30.u98o9-J7hMTWVT9w1NmcFidch-qHKuO2RrxrPKN-bxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});